name: Make new release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:

  semver_labels:
    name: Read semver labels from merged PR
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      semver_app: ${{ steps.semver_labels.outputs.semver_app }}
      semver_chart: ${{ steps.semver_labels.outputs.semver_chart }}
      skip_release: ${{ steps.semver_labels.outputs.skip_release }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
      - uses: ./.github/actions/check-pr-semver-labels
        id: semver_labels
        with:
          github_token: ${{ secrets.BOT_GITHUB_TOKEN}}

  semver_update:
    if: ${{needs.semver_labels.outputs.skip_release == 'False'}}
    name: Update semver for every eligible file of repo (helm charts, package.json , etc.)
    runs-on: ubuntu-latest
    needs: semver_labels
    environment: prod
    outputs:
      app_version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout release branch 
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}  
      
      - name: Setup git author
        run: |
          git config --global user.email "${{ secrets.BOT_GIT_MAIL }}" && git config --global user.name "${{ secrets.BOT_GIT_USER }}"
      
      - name: Setup Node.js 22
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version: '22'
      
      - name: Set branch
        run: |
          echo "BRANCH=-${{github.ref_name}}" >> $GITHUB_ENV
        if: ${{ github.ref_name != 'main' }}
        shell: bash
      
      - id: get_version
        name: Get Version
        run: |
          PACKAGE_FILE="package.json"
          if [[ -f "$PACKAGE_FILE" ]]; then
            echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          fi
        shell: bash
      
      - name: Bump Package Version
        id: bump
        uses: pagopa/github-actions-template/bump-semver@main
        with:
          semver: ${{ needs.semver_labels.outputs.semver_app  }}
          current_version: ${{ env.version }}
      - id: semver
        name: New Version
        run: |   
          echo "new_version=${{ steps.bump.outputs.new_version }}${{env.BRANCH}}" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: Update Helm Version Values
        run: |
          for i in helm/values-*.yaml; do
            [ -f "$i" ] || break
            yq -i ".microservice-chart.image.tag = \"${{steps.semver.outputs.new_version}}\"" "$i"
            git add "$i"
          done
      - name: Update Chart App Version
        run: |
          CHART_FILE="helm/Chart.yaml"
            if [[ -f "$CHART_FILE" ]]; then
              yq -i ".appVersion = \"${{steps.semver.outputs.new_version}}\"" "$CHART_FILE"
              git add "$CHART_FILE"
          fi
      
      - name: Install semver globally
        run: yarn global add semver

      - name: Update Chart Version
        run: |
          RELEASE_CHART_SEMVER=$(echo ${{ needs.semver_labels.outputs.semver_chart }} |  cut -d'-' -f2 )
          CHART_FILE="helm/Chart.yaml"
          CURRENT_CHART_VERSION=$(yq -r '.version' $CHART_FILE)
          if [[ -f "$CHART_FILE" ]]; then
            yq -i ".version = \"$(semver $CURRENT_CHART_VERSION -i $RELEASE_CHART_SEMVER )\"" "$CHART_FILE"
            git add "$CHART_FILE"
          fi
      
      # push new version
      - name: Push New Version of the package.json
        shell: bash
        run: |
          contents="$(jq '.version = "${{ steps.semver.outputs.new_version }}"' package.json)"
          echo -E "${contents}" > package.json
    
          git add .
          git commit -m "Bump to version ${{ steps.semver.outputs.new_version }} [skip ci]"
          git push origin ${{ github.ref_name}}

  github_release:
    if: ${{needs.semver_labels.outputs.skip_release == 'False'}}
    name: Create a New Github Release
    needs: semver_update
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout release branch
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          persist-credentials: false
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          ref: 'main'
      - name: Set Up Github Release
        id: setup_github_release
        run: |
          CHART_FILE="helm/Chart.yaml"
          chart_version=$(yq -r '.version' $CHART_FILE)
          HEAD_SHA=$(git rev-parse HEAD)
          TAG="$chart_version"
          TITLE="Release $chart_version"
          echo "HEAD_SHA=$HEAD_SHA" >> $GITHUB_OUTPUT
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "TITLE=$TITLE" >> $GITHUB_OUTPUT
        # create new github release
      - name: Create New Github Release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 #v1.16.0
        with:
          commit: ${{ steps.setup_github_release.outputs.HEAD_SHA }}
          tag: ${{ steps.setup_github_release.outputs.TAG }}
          name: ${{ steps.setup_github_release.outputs.TITLE }}
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          makeLatest: true
          generateReleaseNotes: true
          draft: false
          prerelease: false